version: '3'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    command: 
      dist/server.js
    depends_on:
      - redis
    links:
      - redis
  redis:
    image: bitnami/redis:6.2.6
    container_name: redis
    environment:
     - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'